### ISSUE TITLE
Refactor AngularJS controllers. 

### ISSUE THREAD

**Issue by MishaHusiuk** [MishaHusiuk/Blog#10]
Now all AngularJS controllers are thick, and stored in single file. To make them more thin, do the following:  

- [ ]  Distinguish all controllers by their own files;

- [ ] Move all business logic to services from controllers;

**Comment by MishaHusiuk** [comment]
Estimate: 1 hour

**Comment by kot91** [comment]
@MishaHusiuk Which files are you specifying? I'd like to take a look at this.

**Comment by MishaHusiuk** [comment]
@kot91 File Blog/Content/js/Controllers/ClientController.js
I have already started working on that, but if you lake a look and give some feenback or participate, this would be cool.

**Comment by kot91** [comment]
@MishaHusiuk great! I'll give it a go and I'll try to give input around the end of the page so as to not overlap if I do have suggested changes :)

**Comment by MishaHusiuk** [comment]
@kot91 I have already got one solution can you take a look a it? 
Review my Pull request https://github.com/MishaHusiuk/Blog/pull/11

**Comment by kot91** [comment]
@MishaHusiuk This is pretty far over my head, unfortunately. I'm still working through it so I don't know that I would have constructive criticism for you at the moment.

Apologies!

**Comment by MishaHusiuk** [comment]
@kot91 That's okay, you can finish your verion, I'll not merge my solution, and when you will be done, we can compare and merge best from mine, and yours.

**Comment by kot91** [comment]
@MishaHusiuk I appreciate the opportunity, however I have not started and do not have a complete understanding of how I would go about it.

That said, I intend on giving it a go but certainly not in a production scenario. 

If I can produce something I will gladly accept the invitation :) Thanks!

**Comment by MishaHusiuk** [comment]
@kot91 If it's interesting for you, [there](https://github.com/MishaHusiuk/Blog/issues/9) is another issue, that I would be glad if you participate.
